id: git-config

info:
  name: logs file configuration
  author: suga
  severity: critical
  description: Web logs file disclosures.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  tags: config,logs,exposure
  metadata:
    max-request: 4

http:
  - method: GET
    path:
      - "{{BaseURL}}/log/production.log
      - "{{BaseURL}}/config/app_env.yml
      - "{{BaseURL}}/config/database.yml
      - "{{BaseURL}}/config/secrets.yml

    matchers-condition: and
     matchers:
      - type: status
        status:
          - 200
